**Integer Embedding**

In [ ]:
import numpy as np
mycorpus = ["I am playing cricket","He is playing football"]

In [ ]:
import keras
from keras.preprocessing.text import Tokenizer
mytokenizer = Tokenizer()

In [ ]:
mytokenizer.fit_on_texts(mycorpus)

In [ ]:
mytokenizer.word_index

{'playing': 1, 'i': 2, 'am': 3, 'cricket': 4, 'he': 5, 'is': 6, 'football': 7}

In [ ]:
mysequences = mytokenizer.texts_to_sequences(mycorpus)
mysequences

[[2, 3, 1, 4], [5, 6, 1, 7]]

**Keras Embedding**

In [ ]:
from keras.utils import pad_sequences
mypaddedsequence = pad_sequences(mysequences , padding = 'post')
mypaddedsequence

array([[2, 3, 1, 4],
       [5, 6, 1, 7]], dtype=int32)

In [ ]:
from keras import models,layers

model = models.Sequential()
model.add(layers.Embedding(8, output_dim = 3 , input_length = 4))
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 4, 3)              24        
                                                                 
Total params: 24 (96.00 Byte)
Trainable params: 24 (96.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(mypaddedsequence)

1/1 [==============================] - 0s 47ms/step


In [ ]:
pred

array([[[-0.04769829,  0.00709621, -0.02049755],
        [-0.04878923, -0.02713503,  0.01773972],
        [-0.00042593,  0.04070621, -0.02958926],
        [-0.0189827 , -0.02779369, -0.03879531]],

       [[-0.01368458, -0.01571969, -0.03084691],
        [ 0.01435996, -0.01699357, -0.03694355],
        [-0.00042593,  0.04070621, -0.02958926],
        [-0.02062421,  0.02592236,  0.00896502]]], dtype=float32)

In [ ]:
print(mycorpus)

['I am playing cricket', 'He is playing football']


In [ ]:
print(mytokenizer.word_index)

{'playing': 1, 'i': 2, 'am': 3, 'cricket': 4, 'he': 5, 'is': 6, 'football': 7}


**Build a Neural Network using these text embedded values to identify a player as cricket or football**

In [ ]:
import numpy as np
sent_levels = np.array([1,0])

In [ ]:
predictionmodel = models.Sequential()
predictionmodel.add(layers.Embedding(8, output_dim = 3 , input_length = 4))
predictionmodel.add(layers.Flatten())
predictionmodel.add(layers.Dense(1,activation='sigmoid'))

In [ ]:
predictionmodel.compile('adam' , loss = 'binary_crossentropy', metrics=['accuracy'])

In [ ]:
predictionmodel.fit(mypaddedsequence,sent_levels)

1/1 [==============================] - 1s 628ms/step - loss: 0.6926 - accuracy: 1.0000


In [ ]:
predictionmodel

In [ ]:
sent_to_predict = ['I am playing cricket']
sentseq = mytokenizer.texts_to_sequences(sent_to_predict)
pred_data = pad_sequences(sentseq,padding='pre')
pred_data

array([[2, 3, 1, 4]], dtype=int32)

In [ ]:
predictions = (predictionmodel.predict(pred_data) > 0.5).astype("int32")
predictions

1/1 [==============================] - 0s 34ms/step


array([[1]], dtype=int32)